In [1]:
import pandas as pd
import numpy as np

In [2]:
df= pd.read_csv("../db/belly_button_metadata.csv", delimiter=',')
df_belly= pd.read_csv("../db/belly_button_data.csv", delimiter=',')

### <font color =  blue> MetaData </font>

In [3]:
df.head()

,sample,EVENT,ETHNICITY,GENDER,AGE,WFREQ,BBTYPE,LOCATION,COUNTRY012,ZIP012,...,DOG,CAT,IMPSURFACE013,NPP013,MMAXTEMP013,PFC013,IMPSURFACE1319,NPP1319,MMAXTEMP1319,PFC1319
0,940,BellyButtonsScienceOnline,Caucasian,F,24.0,2.0,I,Beaufort/NC,usa,22306,...,no,no,8852.0,37.172222,54.5,NaN,1,NaN,33.990002,25.5
1,941,NaN,Caucasian/Midleastern,F,34.0,1.0,I,Chicago/IL,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,943,BellyButtonsScienceOnline,Caucasian,F,49.0,1.0,I,Omaha/NE,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,944,BellyButtonsScienceOnline,European,M,44.0,1.0,I,NewHaven/CT,usa,7079,...,no,yes,NaN,35.816666,16.0,NaN,0,6567.0,32.403332,28.5
4,945,BellyButtonsScienceOnline,Caucasian,F,48.0,1.0,I,Philidelphia/PA,usa,84404,...,no,no,NaN,37.783333,4.0,NaN,0,5613.0,33.634445,24.0

### Rename Column Headers

In [4]:
df = df.rename(columns={"EVENT":"event", "ETHNICITY":"ethnicity","GENDER":"gender","AGE":"age","WFREQ":"wfreq","BBTYPE":"bbtype","LOCATION":"location","COUNTRY012":"country_012"})
df.head()

,sample,event,ethnicity,gender,age,wfreq,bbtype,location,country_012,ZIP012,...,DOG,CAT,IMPSURFACE013,NPP013,MMAXTEMP013,PFC013,IMPSURFACE1319,NPP1319,MMAXTEMP1319,PFC1319
0,940,BellyButtonsScienceOnline,Caucasian,F,24.0,2.0,I,Beaufort/NC,usa,22306,...,no,no,8852.0,37.172222,54.5,NaN,1,NaN,33.990002,25.5
1,941,NaN,Caucasian/Midleastern,F,34.0,1.0,I,Chicago/IL,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,943,BellyButtonsScienceOnline,Caucasian,F,49.0,1.0,I,Omaha/NE,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,944,BellyButtonsScienceOnline,European,M,44.0,1.0,I,NewHaven/CT,usa,7079,...,no,yes,NaN,35.816666,16.0,NaN,0,6567.0,32.403332,28.5
4,945,BellyButtonsScienceOnline,Caucasian,F,48.0,1.0,I,Philidelphia/PA,usa,84404,...,no,no,NaN,37.783333,4.0,NaN,0,5613.0,33.634445,24.0

In [5]:
df = df.rename(columns={"ZIP012":"zip_012", "COUNTRY1319":"country_1319","ZIP1319":"zip_1319","DOG":"dog","CAT":"cat","IMPSURFACE013":"impsurface_013","NPP013":"npp_013","MMAXTEMP013":"maxtemp_013"})
df.head()

,sample,event,ethnicity,gender,age,wfreq,bbtype,location,country_012,zip_012,...,dog,cat,impsurface_013,npp_013,maxtemp_013,PFC013,IMPSURFACE1319,NPP1319,MMAXTEMP1319,PFC1319
0,940,BellyButtonsScienceOnline,Caucasian,F,24.0,2.0,I,Beaufort/NC,usa,22306,...,no,no,8852.0,37.172222,54.5,NaN,1,NaN,33.990002,25.5
1,941,NaN,Caucasian/Midleastern,F,34.0,1.0,I,Chicago/IL,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,943,BellyButtonsScienceOnline,Caucasian,F,49.0,1.0,I,Omaha/NE,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,944,BellyButtonsScienceOnline,European,M,44.0,1.0,I,NewHaven/CT,usa,7079,...,no,yes,NaN,35.816666,16.0,NaN,0,6567.0,32.403332,28.5
4,945,BellyButtonsScienceOnline,Caucasian,F,48.0,1.0,I,Philidelphia/PA,usa,84404,...,no,no,NaN,37.783333,4.0,NaN,0,5613.0,33.634445,24.0

In [6]:
df = df.rename(columns={"PFC013":"pfc_013", "IMPSURFACE1319":"impsurface_1319","NPP1319":"npp_1319","MMAXTEMP1319":"mmaxtemp_1319","PFC1319":"pfc_1319"})
df.head()

,sample,event,ethnicity,gender,age,wfreq,bbtype,location,country_012,zip_012,...,dog,cat,impsurface_013,npp_013,maxtemp_013,pfc_013,impsurface_1319,npp_1319,mmaxtemp_1319,pfc_1319
0,940,BellyButtonsScienceOnline,Caucasian,F,24.0,2.0,I,Beaufort/NC,usa,22306,...,no,no,8852.0,37.172222,54.5,NaN,1,NaN,33.990002,25.5
1,941,NaN,Caucasian/Midleastern,F,34.0,1.0,I,Chicago/IL,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,943,BellyButtonsScienceOnline,Caucasian,F,49.0,1.0,I,Omaha/NE,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,944,BellyButtonsScienceOnline,European,M,44.0,1.0,I,NewHaven/CT,usa,7079,...,no,yes,NaN,35.816666,16.0,NaN,0,6567.0,32.403332,28.5
4,945,BellyButtonsScienceOnline,Caucasian,F,48.0,1.0,I,Philidelphia/PA,usa,84404,...,no,no,NaN,37.783333,4.0,NaN,0,5613.0,33.634445,24.0

In [7]:
list_of_columns = ["age","wfreq","zip_012","zip_1319","impsurface_013","npp_013","maxtemp_013","impsurface_1319","npp_1319","mmaxtemp_1319","pfc_1319"]

In [8]:
i = 0

while i <= len(list_of_columns):
    for cols in list_of_columns: 
        df[cols] = df[cols].fillna(0)
    i = i + 1

In [9]:
df.head()

,sample,event,ethnicity,gender,age,wfreq,bbtype,location,country_012,zip_012,...,dog,cat,impsurface_013,npp_013,maxtemp_013,pfc_013,impsurface_1319,npp_1319,mmaxtemp_1319,pfc_1319
0,940,BellyButtonsScienceOnline,Caucasian,F,24.0,2.0,I,Beaufort/NC,usa,22306,...,no,no,8852.0,37.172222,54.5,NaN,1,0.0,33.990002,25.5
1,941,NaN,Caucasian/Midleastern,F,34.0,1.0,I,Chicago/IL,NaN,0,...,NaN,NaN,0.0,0.000000,0.0,NaN,0,0.0,0.000000,0.0
2,943,BellyButtonsScienceOnline,Caucasian,F,49.0,1.0,I,Omaha/NE,NaN,0,...,NaN,NaN,0.0,0.000000,0.0,NaN,0,0.0,0.000000,0.0
3,944,BellyButtonsScienceOnline,European,M,44.0,1.0,I,NewHaven/CT,usa,7079,...,no,yes,0.0,35.816666,16.0,NaN,0,6567.0,32.403332,28.5
4,945,BellyButtonsScienceOnline,Caucasian,F,48.0,1.0,I,Philidelphia/PA,usa,84404,...,no,no,0.0,37.783333,4.0,NaN,0,5613.0,33.634445,24.0

In [10]:
df = df.dropna(axis=1, how='all')

In [11]:
df['dog'] = df['dog'].fillna('none')
df['cat'] = df['cat'].fillna('none')

In [12]:
df.dropna(subset=['event'], inplace=True)

In [13]:
df.head()

,sample,event,ethnicity,gender,age,wfreq,bbtype,location,country_012,zip_012,...,zip_1319,dog,cat,impsurface_013,npp_013,maxtemp_013,impsurface_1319,npp_1319,mmaxtemp_1319,pfc_1319
0,940,BellyButtonsScienceOnline,Caucasian,F,24.0,2.0,I,Beaufort/NC,usa,22306,...,22306,no,no,8852.0,37.172222,54.5,1,0.0,33.990002,25.5
2,943,BellyButtonsScienceOnline,Caucasian,F,49.0,1.0,I,Omaha/NE,NaN,0,...,0,none,none,0.0,0.000000,0.0,0,0.0,0.000000,0.0
3,944,BellyButtonsScienceOnline,European,M,44.0,1.0,I,NewHaven/CT,usa,7079,...,8822,no,yes,0.0,35.816666,16.0,0,6567.0,32.403332,28.5
4,945,BellyButtonsScienceOnline,Caucasian,F,48.0,1.0,I,Philidelphia/PA,usa,84404,...,96025,no,no,0.0,37.783333,4.0,0,5613.0,33.634445,24.0
5,946,BellyButtonsScienceOnline,Caucasian,F,42.0,3.0,I,Deerfield/MA,usa,12538,...,12538,no,yes,0.0,34.761112,15.5,0,6273.0,29.403334,67.5

In [14]:
list_of_cols_upper = ["gender","bbtype","country_012","country_1319"]

In [15]:
i = 0

while i <= len(list_of_cols_upper):
    for cols in list_of_cols_upper: 
        df[cols] = df[cols].str.upper()
    i = i + 1

In [16]:
df.head()

,sample,event,ethnicity,gender,age,wfreq,bbtype,location,country_012,zip_012,...,zip_1319,dog,cat,impsurface_013,npp_013,maxtemp_013,impsurface_1319,npp_1319,mmaxtemp_1319,pfc_1319
0,940,BellyButtonsScienceOnline,Caucasian,F,24.0,2.0,I,Beaufort/NC,USA,22306,...,22306,no,no,8852.0,37.172222,54.5,1,0.0,33.990002,25.5
2,943,BellyButtonsScienceOnline,Caucasian,F,49.0,1.0,I,Omaha/NE,NaN,0,...,0,none,none,0.0,0.000000,0.0,0,0.0,0.000000,0.0
3,944,BellyButtonsScienceOnline,European,M,44.0,1.0,I,NewHaven/CT,USA,7079,...,8822,no,yes,0.0,35.816666,16.0,0,6567.0,32.403332,28.5
4,945,BellyButtonsScienceOnline,Caucasian,F,48.0,1.0,I,Philidelphia/PA,USA,84404,...,96025,no,no,0.0,37.783333,4.0,0,5613.0,33.634445,24.0
5,946,BellyButtonsScienceOnline,Caucasian,F,42.0,3.0,I,Deerfield/MA,USA,12538,...,12538,no,yes,0.0,34.761112,15.5,0,6273.0,29.403334,67.5

In [17]:
df.dtypes

sample               int64
event               object
ethnicity           object
gender              object
age                float64
wfreq              float64
bbtype              object
location            object
country_012         object
zip_012             object
country_1319        object
zip_1319            object
dog                 object
cat                 object
impsurface_013     float64
npp_013            float64
maxtemp_013        float64
impsurface_1319     object
npp_1319           float64
mmaxtemp_1319      float64
pfc_1319           float64
dtype: object

In [18]:
df['impsurface_1319'] = df['impsurface_1319'].replace("'NA'",0).astype('float64')

In [19]:
df.dtypes

sample               int64
event               object
ethnicity           object
gender              object
age                float64
wfreq              float64
bbtype              object
location            object
country_012         object
zip_012             object
country_1319        object
zip_1319            object
dog                 object
cat                 object
impsurface_013     float64
npp_013            float64
maxtemp_013        float64
impsurface_1319    float64
npp_1319           float64
mmaxtemp_1319      float64
pfc_1319           float64
dtype: object

In [20]:
df.to_csv('../db/belly_button_summarized.csv', sep=',' , encoding= 'utf-8', index=False)

### Import DF to Postgres

In [21]:
from sqlalchemy import create_engine
engine = create_engine ('postgresql://postgres:postgres@localhost:5432/project_databases')
df.to_sql('belly_button_data', engine)

### <font color =  blue> BellyData </font>

In [22]:
df_belly.head()

,otu_id,otu_label,940,941,943,944,945,946,947,948,...,1562,1563,1564,1572,1573,1574,1576,1577,1581,1601
0,1,Archaea;Euryarchaeota;Halobacteria;Halobacteri...,0,0,0,0,0,0,0,0.0,...,0,0,0,0,0,0,0,0,0,0
1,2,Archaea;Euryarchaeota;Halobacteria;Halobacteri...,0,0,0,0,0,0,0,0.0,...,0,0,0,0,0,0,0,0,0,0
2,3,Archaea;Euryarchaeota;Halobacteria;Halobacteri...,0,0,0,0,0,0,0,0.0,...,0,0,0,0,0,0,0,0,0,0
3,4,Archaea;Euryarchaeota;Methanobacteria;Methanob...,0,0,0,0,0,0,0,0.0,...,0,0,0,0,0,0,0,0,0,0
4,5,Archaea;Euryarchaeota;Methanobacteria;Methanob...,0,0,0,0,0,0,0,0.0,...,0,0,0,0,0,0,0,0,0,0

In [23]:
## the bacteria have the same prefix, thus is in order in to get the unique lables for each sample
## I've extracted the last character after ";" to indentify the bacteria, rather than the whole name itself. 
## for readability 

i= 0
button_columns = []

for row in df_belly["otu_label"]: 
    button_columns.append(row.split(";")[-1])
    
    i = i + 1 
    
    
print(button_columns)

['Halococcus', 'Halococcus', 'Natronorubrum', 'Methanobrevibacter', 'Methanobrevibacter', 'Methanobrevibacter', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Bacteria', 'Gp1', 'Gp1', 'Gp1', 'Gp1', 'Gp1', 'Gp10', 'Gp16', 'Gp16', 'Gp16', 'Gp2', 'Gp2', 'Gp2', 'Gp2', 'Gp2', 'Gp2', 'Gp3', 'Gp3', 'Gp3', 'Gp3', 'Gp4', 'Gp4', 'Gp6', 'Actinobacteria', 'Actinobacteria', 'Actinobacteria', 'Actinobacteria', 'Actinobacteria', 'Actinobacteria', 'Actinobacteria', 'Actinobacteria', 'Actinobacteria', 'Acidimicrobiales', 'Iamia', 'Ilumatobacter', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetales', 'Actinomycetaceae', 'Actinomycetaceae', 'Actinomycetaceae', 'Actinobaculum', 'Actinobaculum', 'Actinobaculum', 'Actinomyces', 'Actinomyces', 'Actinomyces', 'Actinomyces', 'Actinomyces', 'Actinomyces', 'Actinomyces', 'Actinomyces', 'Arcanobacterium', 'Mobiluncus', 'Mobiluncus', 'Mobiluncus', 'Mobiluncus', 'Mobiluncus', 'Mobiluncus', 'Mobiluncus', 'Mobiluncus', 'Mobiluncus', 'Mobiluncus', 'Mobiluncus', 'Mobiluncus', 'Varibaculum', 'Varibaculum', 'Varibaculum', 'Varibaculum', 'Varibaculum', 'Varibaculum', 'Varibaculum', 'Varibaculum', 'Varibaculum', 'Varibaculum', 'Varibaculum', 'Varibaculum', 'Varibaculum', 'Varibaculum', 'Varibaculum', 'Varibaculum', 'Varibaculum', 'Varibaculum', 'Varibaculum', 'Varibaculum', 'Varibaculum', 'Varibaculum', 'Georgenia', 'Brevibacterium', 'Brevibacterium', 'Brevibacterium', 'Cellulomonadaceae', 'Corynebacteriaceae', 'Corynebacteriaceae', 'Corynebacteriaceae', 'Corynebacteriaceae', 'Corynebacteriaceae', 'Corynebacteriaceae', 'Corynebacteriaceae', 'Corynebacteriaceae', 'Corynebacteriaceae', 'Corynebacteriaceae', 'Corynebacteriaceae', 'Corynebacteriaceae', 'Corynebacteriaceae', 'Corynebacteriaceae', 'Corynebacteriaceae', 'Corynebacteriaceae', 'Corynebacteriaceae', 'Corynebacteriaceae', 'Corynebacteriaceae', 'Corynebacteriaceae', 'Corynebacteriaceae', 'Corynebacteriaceae', 'Corynebacteriaceae', 'Corynebacteriaceae', 'Corynebacteriaceae', 'Corynebacteriaceae', 'Corynebacteriaceae', 'Corynebacteriaceae', 'Corynebacteriaceae', 'Corynebacteriaceae', 'Corynebacteriaceae', 'Corynebacterium', 'Corynebacterium', 'Corynebacterium', 'Corynebacterium', 'Corynebacterium', 'Corynebacterium', 'Corynebacterium', 'Corynebacterium', 'Corynebacterium', 'Corynebacterium', 'Corynebacterium', 'Corynebacterium', 'Corynebacterium', 'Corynebacterium', 'Corynebacterium', 'Corynebacterium', 'Corynebacterium', 'Corynebacterium', 'Corynebacterium', 'Corynebacterium', 'Corynebacterium', 'Corynebacterium', 'Corynebacterium', 'Corynebacterium', 'Corynebacterium', 'Corynebacterium', 'Corynebacterium', 'Corynebacterium', 'Turicella', 'Turicella', 'Turicella', 'Dermabacteraceae', 'Dermabacteraceae', 'Dermabacteraceae', 'Dermabacteraceae', 'Brachybacterium', 'Brachybacterium', 'Dermabacter', 'Dermabacter', 'Dermabacter', 'Dermabacter', 'Dermabacter', 'Dermabacter', 'Dermabacter', 'Dermabacter', 'Dermabacter', 'Dermabacter', 'Dermabacter', 'Dermabacter', 'Dermabacter', 'Dermabacter', 'Dermacoccus', 'Dermacoccus', 'Kytococcus', 'Kytococcus', 'Dietzia', 'Intrasporangiaceae', 'Arsenicicoccus', 'Janibacter', 'Ornithinimicrobium', 'Phycicoccus', 'Terrabacter', 'Kineosporiaceae', 'Quadrisphaera', 'Microbacteriaceae', 'Microbacteriaceae', 'Microbacteriaceae', 'Microbacteriaceae', 'Microbacteriaceae', 'Microbacteriaceae', 'Microbacteriaceae', 'Microbacteriaceae', 'Microbacteriaceae', 'Microbacteriaceae', 'Microbacteriaceae', 'Microbacteriaceae', 'Microbacteriaceae', 'Microbacteriaceae', 'Microbacteriaceae', 'Microbacteriaceae', 'Microbacteriaceae', 'Microbacteriaceae', 'Zimmermannella', 'Micrococcaceae', 'Micrococcaceae', 'Micrococcaceae', 'Micrococcaceae', 'Micrococcaceae', 'Micrococcaceae', 'Micrococcaceae', 'Micrococcaceae', 'Micrococcaceae', 'Micrococcaceae', 'Micrococcaceae', 'Arthrobacter', 'Kocuria', 'Micrococcus', 'Rothia', 'Rothia', 'Ruania', 'Micromonosporaceae', 'Virgisporangium', 'Nakamurellaceae', 'Gordonia', 'Millisia', 'Rhodococcus', 'Rhodococcus', 'Rhodococcus', 'Rhodococcus', 'Williamsia', 'Nocardioidaceae', 'Nocardioidaceae', 'Nocardioidaceae', 'Nocardioidaceae', 'Nocardioidaceae', 'Nocardioidaceae', 'Nocardioidaceae', 'Nocardioidaceae', 'Nocardioidaceae', 'Aeromicrobium', 'Marmoricola', 'Nocardioides', 'Nocardioides', 'Propionibacteriaceae', 'Propionibacteriaceae', 'Propionibacterium', 'Propionibacterium', 'Propionibacterium', 'Propionibacterium', 'Pseudonocardiaceae', 'Pseudonocardiaceae', 'Actinomycetospora', 'Saccharopolyspora', 'Sciscionella', 'Streptomycetaceae', 'Thermomonosporaceae', 'Bifidobacteriaceae', 'Alloscardovia', 'Bifidobacterium', 'Gardnerella', 'Gardnerella', 'Coriobacteriaceae', 'Atopobium', 'Atopobium', 'Atopobium', 'Atopobium', 'Rubrobacter', 'Rubrobacter', 'Solirubrobacterales', 'Solirubrobacterales', 'Solirubrobacterales', 'Conexibacter', 'Conexibacter', 'Solirubrobacter', 'Bacteroidetes', 'Bacteroidetes', 'Bacteroidetes', 'Bacteroidetes', 'Bacteroidetes', 'Bacteroidetes', 'Bacteroidetes', 'Bacteroidetes', 'Bacteroidetes', 'Bacteroidetes', 'Bacteroidetes', 'Bacteroidetes', 'Bacteroidetes', 'Bacteroidetes', 'Bacteroidetes', 'Bacteroidetes', 'Bacteroidetes', 'Bacteroidetes', 'Bacteroidetes', 'Bacteroidetes', 'Bacteroidetes', 'Bacteroidetes', 'Bacteroidetes', 'Bacteroidetes', 'Bacteroidetes', 'Bacteroidetes', 'Bacteroidetes', 'Bacteroidetes', 'Bacteroidetes', 'Bacteroidetes', 'Bacteroidetes', 'Bacteroidetes', 'Bacteroidetes', 'Bacteroidetes', 'Bacteroidetes', 'Bacteroidetes', 'Bacteroidetes', 'Bacteroidetes', 'Bacteroidales', 'Bacteroidales', 'Bacteroidales', 'Bacteroidales', 'Bacteroidales', 'Bacteroidales', 'Bacteroides', 'Bacteroides', 'Bacteroides', 'Phocaeicola', 'Phocaeicola', 'Phocaeicola', 'Porphyromonadaceae', 'Porphyromonadaceae', 'Porphyromonadaceae', 'Porphyromonadaceae', 'Porphyromonadaceae', 'Porphyromonadaceae', 'Porphyromonadaceae', 'Porphyromonadaceae', 'Porphyromonadaceae', 'Porphyromonadaceae', 'Porphyromonadaceae', 'Porphyromonadaceae', 'Porphyromonadaceae', 'Porphyromonadaceae', 'Porphyromonadaceae', 'Barnesiella', 'Parabacteroides', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Porphyromonas', 'Prevotellaceae', 'Prevotellaceae', 'Prevotellaceae', 'Prevotellaceae', 'Prevotellaceae', 'Prevotellaceae', 'Prevotellaceae', 'Prevotellaceae', 'Prevotellaceae', 'Prevotellaceae', 'Prevotellaceae', 'Prevotellaceae', 'Prevotellaceae', 'Prevotellaceae', 'Prevotellaceae', 'Prevotellaceae', 'Prevotellaceae', 'Prevotellaceae', 'Prevotellaceae', 'Prevotellaceae', 'Prevotellaceae', 'Prevotellaceae', 'Hallella', 'Pa

In [24]:
#inserted column of otu summary labels as the first real daata column to eventually act as primary index value for charts

df_belly.insert(loc=1, column='otu_summary_label', value=button_columns)
df_belly.head()

,otu_id,otu_summary_label,otu_label,940,941,943,944,945,946,947,...,1562,1563,1564,1572,1573,1574,1576,1577,1581,1601
0,1,Halococcus,Archaea;Euryarchaeota;Halobacteria;Halobacteri...,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2,Halococcus,Archaea;Euryarchaeota;Halobacteria;Halobacteri...,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,3,Natronorubrum,Archaea;Euryarchaeota;Halobacteria;Halobacteri...,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,Methanobrevibacter,Archaea;Euryarchaeota;Methanobacteria;Methanob...,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,5,Methanobrevibacter,Archaea;Euryarchaeota;Methanobacteria;Methanob...,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [25]:
# to drop csv index value for rows and descriptive otu label
df_belly_button_data = df_belly.drop(columns = ["otu_id","otu_label"])

In [26]:
df_belly_button_data.head()

,otu_summary_label,940,941,943,944,945,946,947,948,949,...,1562,1563,1564,1572,1573,1574,1576,1577,1581,1601
0,Halococcus,0,0,0,0,0,0,0,0.0,0,...,0,0,0,0,0,0,0,0,0,0
1,Halococcus,0,0,0,0,0,0,0,0.0,0,...,0,0,0,0,0,0,0,0,0,0
2,Natronorubrum,0,0,0,0,0,0,0,0.0,0,...,0,0,0,0,0,0,0,0,0,0
3,Methanobrevibacter,0,0,0,0,0,0,0,0.0,0,...,0,0,0,0,0,0,0,0,0,0
4,Methanobrevibacter,0,0,0,0,0,0,0,0.0,0,...,0,0,0,0,0,0,0,0,0,0

In [27]:
#sort summary labels in asc order
df_belly_button_data.sort_values(by="otu_summary_label", ascending=True)

,otu_summary_label,940,941,943,944,945,946,947,948,949,...,1562,1563,1564,1572,1573,1574,1576,1577,1581,1601
1875,Abiotrophia,0,0,0,0,0,0,0,0.0,0,...,0,0,0,0,0,0,0,0,0,0
1876,Abiotrophia,0,0,0,0,0,0,0,0.0,0,...,0,0,0,0,0,0,0,0,0,1
3247,Acetobacter,0,0,0,0,0,0,0,0.0,0,...,0,0,0,0,0,0,0,0,0,0
3246,Acetobacteraceae,0,0,0,0,0,0,0,0.0,0,...,0,0,0,0,0,0,0,0,0,0
3244,Acetobacteraceae,0,0,0,0,0,0,0,0.0,0,...,0,0,0,0,0,0,0,0,0,0
3243,Acetobacteraceae,0,0,0,0,0,0,0,0.0,0,...,0,0,0,0,0,0,0,0,0,0
3242,Acetobacteraceae,0,0,0,0,0,0,0,0.0,0,...,0,0,0,0,0,0,0,0,0,0
3245,Acetobacteraceae,0,0,0,0,0,0,0,0.0,0,...,0,0,0,0,0,0,0,0,0,0
3240,Acetobacteraceae,0,0,0,0,0,0,0,0.0,0,...,0,0,0,0,0,0,0,0,0,0
3239,Acetobacteraceae,0,0,0,0,0,0,0,0.0,0,...,0,0,1,0,0,0,0,0,0,0
3238,Acetobacteraceae,0,0,0,0,0,0,0,0.0,0,...,0,0,0,0,0,0,0,0,0,0
3237,Acetobacteraceae,0,0,0,0,0,0,0,0.0,0,...,0,0,0,0,0,0,0,0,0,0
3236,Acetobacteraceae,0,0,0,0,0,0,0,0.0,0,...,0,0,0,0,0,0,0,0,0,0
3235,Acetobacteraceae,0,0,0,0,0,0,0,0.0,0,...,0,0,0,0,0,0,1,0,0,0
3241,Acetobacteraceae,0,0,0,0,0,0,0,0.0,0,...,0,0,0,0,0,0,0,0,0,0
550,Acidimicrobiales,0,0,0,0,0,0,0,0.0,0,...,0,0,0,0,0,0,0,0,0,0
3541,Acinetobacter,0,0,0,0,0,0,0,0.0,0,...,0,0,0,0,0,0,0,1,0,0
3547,Acinetobacter,0,0,0,0,0,0,0,0.0,0,...,0,0,0,0,0,0,0,0,0,0
3546,Acinetobacter,0,0,0,0,0,0,0,0.0,0,...,0,0,0,0,0,0,0,0,0,0
3545,Acinetobacter,0,0,0,0,0,0,0,0.0,0,...,0,0,0,0,0,0,0,0,0,0
3544,Acinetobacter,0,0,0,0,0,0,0,0.0,0,...,0,0,0,0,0,0,0,0,0,0
3543,Acinetobacter,0,0,0,0,0,0,0,0.0,0,...,0,0,0,0,0,0,0,0,0,0
3542,Acinetobacter,0,0,0,0,0,0,0,0.0,0,...,0,0,0,0,0,0,0,0,0,0
3540,Acinetobacter,0,0,0,0,0,0,0,0.0,0,...,0,0,0,0,0,0,0,0,0,0
3549,Acinetobacter,0,0,0,0,0,0,0,0.0,0,...,0,0,0,0,0,0,0,0,0,0
3538,Acinetobacter,0,0,0,0,0,0,0,0.0,0,...,0,0,0,0,0,0,0,0,0,0
3537,Acinetobacter,0,0,0,4,1,0,0,0.0,0,...,0,0,1,0,1,1,2,2,5,1
3548,Acinetobacter,0,0,0,0,0,0,0,0.0,0,...,0,0,0,0,0,0,0,0,0,0
3539,Acinetobacter,0,0,0,0,0,0,0,0.0,0,...,0,0,0,0,0,0,0,0,0,0
547,Actinobacteria,0,0,0,0,0,0,0,0.0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2952,Veillonellaceae,0,0,0,0,0,0,0,0.0,0,...,0,0,0,0,0,0,0,0,0,0
2951,Veillonellaceae,0,0,0,0,0,0,0,0.0,0,...,0,0,0,0,0,0,0,0,0,0
2973,Veillonellaceae,0,0,0,0,0,0,0,0.0,0,...,0,0,0,0,0,0,0,0,0,0
2974,Veillonellaceae,0,0,0,0,0,0,0,0.0,0,...,0,0,0,0,0,0,0,0,0,1
2975,Veillonellaceae,0,0,0,0,0,0,0,0.0,0,...,0,0,0,0,0,0,0,0,0,0
2976,Veillonellaceae,0,0,0,0,0,0,0,0.0,0,...,0,0,0,0,0,0,0,0,0,0
2977,Veillonellaceae,0,0,0,0,0,0,0,0.0,0,...,0,0,0,0,0,0,0,0,0,0
2978,Veillonellaceae,0,0,0,0,0,0,0,0.0,0,...,0,0,0,0,0,0,0,0,0,0
2971,Veillonellaceae,0,0,0,0,0,0,0,0.0,0,...,0,0,0,0,0,0,0,0,0,1
2953,Veillonellaceae,0,0,0,0,0,0,0,0.0,0,...,0,0,0,0,0,0,0,0,0,0
3662,Verrucomicrobium,0,0,0,0,0,0,0,0.0,0,...,0,0,0,0,0,0,0,0,0,0
1018,Virgisporangium,0,0,0,0,0,0,0,0.0,0,...,0,0,0,0,0,0,0,0,0,0
3354,Wautersia,0,0,0,0,0,0,0,0.0,0,...,0,0,0,0,0,0,0,0,0,0
1367,Wautersiella,0,0,0,0,0,0,0,0.0,0,...,0,0,0,0,0,0,0,0,0,0
1907,Weissella,0,0,0,0,0,0,0,0.0,0,...,0,0,0,0,0,0,0,0,0,0
1026,Williamsia,0,0,0,0,0,0,0,0.0,0,...,0,0,0,0,0,0,0,0,0,0
3592,Xanthomonadaceae,0,0,0,0,0,0,0,0.0,0,...,0,0,1,0,0,0,0,0,0,0
3581,Xanthomonadaceae,0,0,0,0,0,0,0,0.0,0,...,0,0,0,0,0,0,0,0,0,0
3582,Xanthomonadaceae,0,0,0,0,0,0,0,0.0,0,...,0,0,0,0,0,0,0,0,0,0
3583,Xanthomonadaceae,0,0,0,0,0,0,0,0.0,0,...,0,0,0,0,0,0,0,0,0,0
3585,Xanthomonadaceae,0,0,0,0,0,0,0,0.0,0,...,0,0,0,0,0,0,0,0,0,0
3586,Xanthomonadaceae,0,0,0,0,0,0,0,0.0,0,...,0,0,0,0,0,0,0,0,0,0
3587,Xanthomonadaceae,0,0,0,0,0,0,0,0.0,0,...,0,0,0,0,0,0,0,0,0,0
3589,Xanthomonadaceae,0,0,0,0,0,0,0,0.0,0,...,0,0,0,0,0,0,0,0,0,0
3590,Xanthomonadaceae,0,0,0,0,0,0,0,0.0,0,...,0,0,0,0,0,0,0,0,0,0
3591,Xanthomonadaceae,0,0,0,0,0,0,0,0.0,0,...,0,0,0,0,0,0,0,0,0,0
3584,Xanthomonadaceae,0,0,0,0,0,0,0,0.0,0,...,0,0,0,0,0,0,0,0,0,0
3588,Xanthomonadaceae,0,0,0,0,0,0,0,0.0,0,...,0,1,0,0,0,0,0,0,0,0
999,Zimmermannella,0,0,0,0,0,0,0,1.0,0,...,0,0,0,0,0,0,0,0,0,0
3401,Zoogloea,0,0,0,0,0,0,0,0.0,0,...,0,0,0,0,0,0,0,0,0,0

In [28]:
# to create a list of sample columns for groupby function
sample_cols = list(df_belly_button_data.iloc[:,1:].columns)

In [29]:
# to check the list of columns length
len(sample_cols)

153

In [30]:
# to make sure that the list of sample cols do not have duplicate items
len(set(sample_cols))

153

In [31]:
# adjust dataframe to be a groupby summary of the summarized label per sample size
belly_button_df = df_belly_button_data.groupby('otu_summary_label')[sample_cols].sum().reset_index()

In [32]:
belly_button_df.head()

,otu_summary_label,940,941,943,944,945,946,947,948,949,...,1562,1563,1564,1572,1573,1574,1576,1577,1581,1601
0,Abiotrophia,0,0,0,0,0,0,0,0.0,0,...,0,0,0,0,0,0,0,0,0,1
1,Acetobacter,0,0,0,0,0,0,0,0.0,0,...,0,0,0,0,0,0,0,0,0,0
2,Acetobacteraceae,0,0,0,0,0,0,0,0.0,0,...,0,0,1,0,0,0,1,0,0,0
3,Acidimicrobiales,0,0,0,0,0,0,0,0.0,0,...,0,0,0,0,0,0,0,0,0,0
4,Acinetobacter,0,0,0,4,1,0,0,0.0,0,...,0,0,1,0,1,1,2,3,5,1

In [33]:
engine = create_engine ('postgresql://postgres:postgres@localhost:5432/project_databases')
belly_button_df.to_sql('belly_button_metadata', engine)

In [34]:
belly_button_df.to_csv('../db/belly_button_metadata_summarized.csv', sep=',' , encoding= 'utf-8', index=False)